script Entry:
	Name(`???`)
	switch GetMap():
		case 1, 3:
			run TeleportOptions
		case 2:
			if HasItem(`SecretShopToken`) gte 1:
				run ShopOptions
			else:
				Dialog(`Way the wind blows...`)
				end
	Dialog(`Howdy there, fancy seeing you here.`)

script ShopOptions:
	# TODO I can't figure out a good name, figure it out
	Name(`GoothBert`)
	Dialog(`Ah I see you have the Secret Shop Token! Fancy some of my warez will ya?`)
	OpenShop(`GoothBert`)

script TeleportOptions:
	switch Prompt(`Would you like to go to the secret tree?`, `Yes`, `No`):
		case `Yes`:
			Dialog(`Away we go!`)
			Teleport(2, `Entrance`)
		case `No`:
			Dialog(`Alright, I'll be here any time.`)
